### ISSUE TITLE
Display frequency, UTC Date time, and other information for image

### ISSUE THREAD

**Issue by innattar** [innattar/sstv_uploader#2]
Consider displaying additional information along with the uploaded image:
* Frequency
* UTC Date time
* SNR
* Duration
* Any other fun Ham metrics

Some of these programs can extract the Hams call from the image (maybe it's In-band data?).  Display that too if possible.

**Comment by anjumun** [comment]
@innattar can the program that you use to make these images add this data into the image exif data?

**Comment by innattar** [comment]
@anjumun no EXIF data in PNG (just learned that myself yesterday).  I hacked something together to handle this using imagemagick.  It's in master now.  However it's leaving me wanting to clean up the code even more :)

Going to close this issue as the now falls to innattar/qsstv to output any new metadata.  This hack will display whatever qsstv emits as metadata.

EX:
![image](https://user-images.githubusercontent.com/61792056/93714648-34250780-fb32-11ea-96c8-07432bb7acf3.png)
